apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: datanode
  name: datanode
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datanode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: datanode
    spec:
      containers:
        - env:
            - name: SERVICE_PRECONDITION
              value: namenode:9870
          envFrom:
            - configMapRef:
                name: hadoop-env
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          name: datanode
          ports:
            - containerPort: 9864
              protocol: TCP
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: hadoop-datanode
      restartPolicy: Always
      volumes:
        - name: hadoop-datanode
          persistentVolumeClaim:
            claimName: hadoop-datanode
