apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: datanode
  name: datanode
  namespace: data
spec:
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: datanode
