apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hive-server
  name: hive-server
  namespace: data
spec:
  type: NodePort
  ports:
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    io.kompose.service: hive-server
