apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: hive-metastore-postgresql
  name: hive-metastore-postgresql
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore-postgresql
  template:
    metadata:
      labels:
        io.kompose.service: hive-metastore-postgresql
    spec:
      containers:
        - image: bde2020/hive-metastore-postgresql:2.3.0
          name: hive-metastore-postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
