apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
  namespace: data
spec:
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
  selector:
    io.kompose.service: hive-metastore

---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    io.kompose.service: hive-metastore-postgresql
#  name: hive-metastore-postgresql
#  namespace: data
#spec:
#  ports:
#    - name: "5432"
#      port: 5432
#      targetPort: 5432
#  selector:
#    io.kompose.service: hive-metastore-postgresql

