apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: namenode
  name: namenode
  namespace: data
spec:
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "9010"
      port: 9010
      targetPort: 9000
  selector:
    io.kompose.service: namenode
