apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: presto-coordinator
  name: presto-coordinator
  namespace: data
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    io.kompose.service: presto-coordinator
