apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: resourcemanager
  name: resourcemanager
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: resourcemanager
  template:
    metadata:
      labels:
        io.kompose.service: resourcemanager
    spec:
      containers:
        - env:
            - name: SERVICE_PRECONDITION
              value: namenode:9000 namenode:9870 datanode:9864
          envFrom:
            - configMapRef:
                name: hadoop-env
          image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
          name: resourcemanager
      restartPolicy: Always
