apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
  namespace: data
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: spark-worker-1
