apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  template:
    metadata:
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:9000
            - name: INIT_DAEMON_STEP
              value: setup_spark
          #image: bde2020/spark-master:3.0.0-hadoop3.2
          image: neogicel/neogiciel-jupyter:2.04
          name: spark-master
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7077
              protocol: TCP
      restartPolicy: Always
