apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-1
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:9000
            - name: SPARK_MASTER
              value: spark://spark-master:7077
          image: bde2020/spark-worker:3.0.0-hadoop3.2
          name: spark-worker-1
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
